---
title: "Discordで動くalphaXiv Botを作る"
author: "宮森祥行"
date: last-modified
format:
  html:
    code-copy: true
    date-format: "YYYY年M月D日"
    toc: true
    embed-resources: true
bibliography: references.bib
---

　私は先輩にarXivの，例えば私だったらstatistics theoryのページで，毎日新着論文のタイトルをチェックして，興味が湧いたものはちょっと目を通したりというのをコツコツやるといいですよと教えてもらった．しかし3日坊主でやめてしまった．やっぱりトレンドを知ったり自分の世界を広げるのが目的なのだろうからと，全然知らないものにも目を通そうとして面倒になってやめてしまう．  
　そこで安直に思いつくのはAIに2ページほどの日本語に要約させるというものだが，雑な指示だとあまり良いものにならないし，毎日毎論文やるのは結構嫌になる作業である．  
　そこで自動化しようと思うわけだが，いや待てよ，誰か既に作ってるだろと思い調べると案の定見つかった．それがalphaXivである．使い方は簡単で，まずはarXivで読みたい論文のページを開き，そのリンクのarxiv.orgの部分をalphaxiv.orgに書き換える．
移動したら上にあるBlogボタンをクリックする．まだ誰も要約を作成していない場合は，Generate Overviewボタンがあるのでそれをクリックして1-2分待つと，要約が(英語で)作成される．誰かが作っていた場合はいきなりそれが表示される．日本語にしたい場合は中央上部のENボタンをクリックすると，日本語が選べる．(自分が要約を作成した場合はENボタンが出るまでに10秒ほどかかる．また，専門用語の和訳の精度はあまり良くない．)
しかし私はどうしようもなく怠惰なのでこれさえ3日坊主で終えてしまった．一つひとつリンクを書き換えるのが想像以上に面倒なのだ．そこでこのルーティーンを代わってくれるBotを作ることにした．やり方はDeepLの翻訳Botとほぼ同じなので[そちら](https://yoshiyuki-miyamori.github.io/MacBookEnv/5_discord.html)を参照されたい．

# プログラムの作成

　先ほど述べた事情から，arXivのstatistics theoryの新着論文があれば自動でそのタイトルとalphaXivの日本語要約のリンクを送ってくれるBotを作ることが目標である．
このBotにより，当たり前だが通知が来るようになり，さらにリンクを踏むだけで目的のページへ飛べる．そして意外と大きいのが，スマホで読めるようになるのである．(もちろんBotを使わなくてもスマホでできるが，だるくて私には事実上不可能である．)また，リアクションをつけることでチェックした記録をつけることもできる．こういうのは些細なようで案外馬鹿にできない．流石にここまで心理的ハードルを下げたらジムの合間などで毎日チェックできると信じている．

　では実装の話をしよう．arXivは課金システムなどないので，APIは公開されており，自分で取得する必要はないのがDeepLとの違いである．Botのトークンは前と同じように取得すること．
また，今回はDiscordのalphaXiv専用チャンネルに送りたいため，チャンネルIDを取得する必要がある．Discordの設定を開き詳細設定を選択し，開発者モードをオンにする．その後，メッセージを送りたいチャンネルを右クリックし，チャンネルIDをコピーをクリックすれば良い．  
　今回もvibe codingで作成したファイルを[GitHub](https://github.com/yoshiyuki-miyamori/MacBookEnv)にalphaxiv.pyとして置いてある．
先ほどのBotトークンとチャンネルID(必要なら分野や開始時刻/終了時刻も)書き換えてから，前の記事と同じようにターミナルやlaunchdで動かせば良い．導入時には何もメッセージは送られず，次にarXivが更新されたタイミングで初めて動く．discord.pyとrequests以外のパッケージは標準で入っているので`pip install`をする必要はない．またこの二つはDeepL Botでも用いたものなのでdeepl.pyと同じ場所に置く場合は同じ仮想環境をactivateするだけで良い．

::: callout-warning
このプログラムはAPIを利用しているのでAPIの更新と同期しており，ウェブサイトの更新とは同期していない．実際ホームページの更新より数時間遅れるがバグではない．arXivのウェブサイトは平日の10時ごろ(サマータイム中は9時ごろ)に更新されるが，今まで動かした感じだと3時間ほど遅れる．また，最新の論文なのでalphaXiv側の対応が追いつかずリンクがうまくいかないこともあるが，これもバグではなく少し待てば解決する．
:::